services:
  chat-service:
    container_name: chat_service
    build: .
    image: chat_service
    ports:
      - 50002:8080
    volumes:
      - ./chat_service:/usr/src/app
    restart: unless-stopped
