services:
  postgres:
    container_name: chat_service_postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: chat-db
    restart: unless-stopped
    networks:
      - net

  chat-service:
    container_name: chat_service
    build: .
    image: chat_service
    ports:
      - 50002:8080
    volumes:
      - ./chat_service:/usr/src/app
    restart: unless-stopped
    networks:
      - net
    depends_on:
      - postgres

networks:
  net:
    driver: bridge
